// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(UMDatabaseContext))]
    [Migration("20231212173126_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Skeleton.Skeleton", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Skeletons");
                });

            modelBuilder.Entity("Domain.Entities.Skeleton.Skeleton", b =>
                {
                    b.OwnsOne("Domain.Entities.Skeleton.SkeletonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SkeletonId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .HasColumnType("longtext");

                            b1.HasKey("SkeletonId");

                            b1.ToTable("Skeletons");

                            b1.WithOwner()
                                .HasForeignKey("SkeletonId");
                        });

                    b.Navigation("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
